import { FaSchool } from "react-icons/fa";
import { MdSchool, MdWork } from "react-icons/md";

export const experience = [
  {
    id: 1,
    type: "education",
    date: "April 2014 - May 2015",
    icon: <FaSchool />,
    bckgrnd: false,
    title: "Global Public School Kota, Rajasthan",
    subtitle: "Secondary Education",
    desc: "Obtained: 90.25%",
    workdesc: [],
  },
  {
    id: 2,
    type: "education",
    date: "April 2016 - May 2017",
    icon: <FaSchool />,
    bckgrnd: true,
    title: "Global Public School Kota, Rajasthan",
    subtitle: "Senior Secondary Education",
    desc: "Obtained: 69.60%",
    workdesc: [],
  },
  {
    id: 3,
    type: "education",
    date: "July 2017 - July 2021",
    icon: <MdSchool />,
    bckgrnd: false,
    title:
      "NMIMS - Mukesh Patel School of Technology Management & Engineering Shirpur, Maharashtra",
    subtitle: "B.Tech. Computer Science ",
    desc: "Overall CGPA: 3.35/4",
    workdesc: [],
  },
  {
    id: 4,
    type: "work",
    date: "May 2020 - June 2020",
    icon: <MdWork />,
    bckgrnd: true,
    title: "SmartBridge Educational Services Pvt. Ltd. Hyderabad, Telangana",
    subtitle: "Internship",
    desc: "Project Internship",
    workdesc: [
      "Used IBM Watson to write the ML code.",
      "NodeRed to deploy the application.",
    ],
  },
  {
    id: 5,
    type: "work",
    date: "May 2020 - June 2020",
    icon: <MdWork />,
    bckgrnd: false,
    title: "CodeSpeedy Technology Pvt. Ltd. Beldanga, West Bengal",
    subtitle: "Internship",
    desc: "C++ Programmer",
    workdesc: [
      "Wrote C++ code, with explanation and diagram for the website post related to DSA.",
    ],
  },
  {
    id: 6,
    type: "work",
    date: "February 2021 - May 2021",
    icon: <MdWork />,
    bckgrnd: true,
    title: "IotIot Pune, Maharashtra",
    subtitle: "Internship",
    desc: "Frontend Developer",
    workdesc: [
      "Completed a frontend using ReactJS.",
      "Worked on Backend to connect NodeJS to C++.",
    ],
  },
];
